Add minimal and desktop false to all incorrect tests in universal
rocky-linux/os-autoinst-distri-rocky pull request #125
Opened 2022-07-10 21:19 UTC by lumarel

# Description

This adds `"PACKAGE_SET": "minimal"` and `"DESKTOP": false` where needed to get the tests passing again.

Fixes #81

# How Has This Been Tested?

```
openqa-cli api -X POST isos ISO=Rocky-9.0-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=9.0 BUILD=-universal-$(git branch --show-current)-$(date +%Y%m%d.%H%M%S).0
```
There are a lot of tests passing now! And a few new issues but mainly a lot of stuff passing! (nothing fails that passed before)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2022-07-10 23:23 UTC, tcooper commented
@lumarel You don't indicated if you are using `DNF_CONTENTDIR` and/or supplying alternate `LOCATION` variable for `install_repository_http_graphical / install_repository_http_variation` in **How has this been tested?** Did you run this `FLAVOR=universal` exactly as you've shown above?

2022-07-11 05:48 UTC, tcooper commented
Another observation... While looking at a recent Rawhide build in the Fedora openQA I noticed that many (most?) tests are using `Fedora Custom Operating System` as the installation environment. The test settings indicated `PACKAGE_SET=default` and `SUBVARIANT=Everything` and in most cases do not supply `DESKTOP=<anything>`.

Such tests end up executing `_console_wait_login`. I think the different meaning of `PACKAGE_SET=default` on the Rocky media and lack of `SUBVARIANT`s is causing much of our login issues.

I am 100% on board with solving that by moving away from using `PACKAGE_SET=default` and assuming/inferring behavior in favor of explicitly specifying `PACKAGE_SET=minimal` and `DESKTOP=false`.

With the possible / (likely) removal of the minimal ISO from Rocky 9 release products this makes even more sense as `FLAVOR=minimal-iso` was the only other place we were explicitly setting `PACKAGE_SET=minimal`.

Currently running through a few of these tests above to get confirmation on to get/give the 👍🏻 .

2022-07-11 06:32 UTC, lumarel commented
> @lumarel You don't indicated if you are using `DNF_CONTENTDIR` and/or supplying alternate `LOCATION` variable for `install_repository_http_graphical / install_repository_http_variation` in **How has this been tested?** Did you run this `FLAVOR=universal` exactly as you've shown above?

Yes you are right there is a difference between what I ran and what I have written above, altered the command now, as the `DNF_CONTENTDIR` parameter was present but no location 👍🏻

2022-07-11 06:34 UTC, lumarel commented
And yes this is only a intermediate change to get the stuff working again, it will take me a few weeks even months until we (I will take the task as proposed so I) have changed that to a better suiting structure 👍🏻

2022-07-17 20:40 UTC, akatch requested changes
I believe `install_sata` needs a similar treatment - it fails at `console_wait_login` but with the GUI login screen shown. Otherwise this looks great!

2022-07-23 00:24 UTC, lumarel commented
@akatch Added the missing bits for `install_sata` now 🙂

2022-07-23 01:17 UTC, lumarel commented
![image](https://user-images.githubusercontent.com/42647570/180584860-e04c9c8a-849c-4e38-b580-295f81161041.png)

The final state!

2022-07-23 04:28 UTC, akatch approved these changes
changes look great, cheers friend

2022-07-23 04:29 UTC, merged